### ISSUE TITLE
Error on preview: "TypeError: value.forEach is not a function"

### ISSUE THREAD

**Issue by rcpinheiro** [shirakaba/tns-template-blank-react#5]
I've tried to install using `tns create my-blank-react --template tns-template-blank-react` and `tns create my-blank-react --template https://github.com/shirakaba/tns-template-blank-react/tarball/master` and alway gives the error (using nativescript 6.9.0):

```Unable to start activity ComponentInfo{org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
TypeError: value.forEach is not a function

StackTrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.nativescript.preview/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: Calling js method onCreate failed
TypeError: value.forEach is not a function
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6251)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by shirakaba** [comment]
@rcpinheiro Wondering what the cause could be. The error stack doesn't make much sense to me.

1. Do you get the same error if you use `tns create my-blank-react --react`?
2. Are you using `tns run android` on a real device, `tns run android` on an emulator, or `tns preview`?

*Note: `tns preview` won't be working right now, as the NativeScript team still need to update their Playground and Preview apps.*

Trying to rule out whether it's an Android-specific issue, a starter template issue, a `babel-loader` issue, a NativeScript 6.9.0 issue, or a combination of all of them.

@t1amat9409 did RNS v1 run fine on Android for you?

**Comment by t1amat9409** [comment]
@shirakaba yes it does. Can he share his code? @rcpinheiro ?
